server:
  port: 8082
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.209.128:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include=*
