server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.209.128:8848
    gateway:
      discovery:
        locator:
          enabled: false
      ##\u662F\u5426\u542F\u7528\u7F51\u5173\u529F\u80FD
      enabled: true
      routes:
        - id: nacos-provider-route
          ##\u5148\u4F7F\u7528\u5730\u5740\uFF0C\u770B\u80FD\u5426\u8BBF\u95EE\u5230 ===>\u53EF\u4EE5\u8BBF\u95EE\u5230
          #          uri: http://192.168.101.251:8082/
          uri: lb://nacos-provider
          ##\u65AD\u8A00\uFF0C\u8FDB\u884C\u4E00\u4E9B\u5224\u65AD\uFF0C\u81EA\u5B9A\u4E49\u65AD\u8A00 \u9700\u8981\u5B9E\u73B0AbstractRoutePredicateFactory  \u4F7F\u7528ZonedDateTime\u83B7\u53D6\u65F6\u95F4\u683C\u5F0F
          predicates:
            ##\u5C06path\u5904\u7684\u8DEF\u5F84\u62FC\u63A5\u5230 uri\u540E\u9762
#            - Path=/aa/**
            - My=30
#            - Before=2021-05-25T11:56:39.135+08:00[Asia/Shanghai]
#            \u591A\u4E2A\u7684\u60C5\u51B5\u4E0B\u53EF\u4EE5\u4F7F\u7528- name\u7684\u5F62\u5F0F\u8FDB\u884C\u914D\u7F6E
#            - name: Cookie
#                args:
#                  name: mycookie
#                  regexp: mycookievalue
#        - id: ORDER-SERVICE           #\u7F51\u5173\u8DEF\u7531\u5230\u8BA2\u5355\u670D\u52A1order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/ORDER-SERVICE/**
#        - id: USER-SERVICE            #\u7F51\u5173\u8DEF\u7531\u5230\u7528\u6237\u670D\u52A1user-service
#          uri: lb://USER-SERVICE
#          predicates:
#              - Pach=/USER-SERVICE/**
  application:
    name: demo-gateway
