server:
  port: 8085
spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.209.128:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullNamePatternMatchesAll=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 192.168.209.128
    port: 6379
